In [1]:
#Problem 1- Array Creation
#1
import numpy as np
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [2]:
#2
import numpy as np
a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#3
import numpy as np
a = np.full((2, 3), 5)
print(a)

[[5 5 5]
 [5 5 5]]


In [4]:
#4
import numpy as np
a = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(a)
print(zeros_like_array)

[[0 0]
 [0 0]]


In [5]:
#5
import numpy as np
a = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(a)
print(ones_like_array)

[[1 1]
 [1 1]]


In [6]:
#6
import numpy as np
new_list =[1, 2, 3, 4]
converted_array = np.array(new_list)
print(converted_array)

[1 2 3 4]


In [7]:
#Problem 2: Array Manipulation: Numerical Ranges and Array indexing
#1
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#2
import numpy as np
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#3
import numpy as np
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#4
import numpy as np
arr = np.random.random(30)
mean = arr.mean()
print(arr, mean)

[0.14836889 0.69330575 0.6671926  0.85135233 0.53432873 0.19824185
 0.51523747 0.63065514 0.11171259 0.88486909 0.06870369 0.95507684
 0.45528428 0.35306182 0.43186378 0.17743027 0.09001098 0.01519855
 0.96809149 0.60292505 0.18959944 0.43762605 0.68212508 0.41222334
 0.94299736 0.88791718 0.03444755 0.39411803 0.58577455 0.4185388 ] 0.47794261834978796


In [11]:
#5
import numpy as np
arr = np.random.random((10, 10))
arr_min = arr.min()
arr_max = arr.max()
print("Minimum Value:", arr_min, "\nMaximum Value:", arr_max)

Minimum Value: 0.0008830054679378474 
Maximum Value: 0.9977941095406213


In [12]:
#6
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#7
import numpy as np
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.array(arr)[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [14]:
#8
import numpy as np
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#9
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [17]:
#Problem-3:Array Operations
#1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_arr = x + y
add_arr1 = v + w
print("Addition of X and Y:", add_arr, "\nAddition of V and W:", add_arr1)

Addition of X and Y: [[ 6  8]
 [10 13]] 
Addition of V and W: [20 22]


In [18]:
#2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sub_arr = x - y
sub_arr1 = v - w
print("Subtraction of X and Y:", sub_arr, "\nSubtraction of V and W:", sub_arr1)

Subtraction of X and Y: [[-4 -4]
 [-4 -3]] 
Subtraction of V and W: [-2 -2]


In [19]:
#3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
mult_arr = x * 9
print(mult_arr)

[[ 9 18]
 [27 45]]


In [20]:
#4
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square_arrX = x**2
square_arrY = y**2
square_arrV = v**2
square_arrW = w**2
print(square_arrX, "\n",square_arrY, "\n",square_arrV,"\n" ,square_arrW)

[[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]] 
 [ 81 100] 
 [121 144]


In [21]:
#5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)
print("Dot Product of V and W:",dot_product_vw, "\nDot Product of X and V: ",dot_product_xv,"\nDot Product of X and Y:",dot_product_xy)

Dot Product of V and W: 219 
Dot Product of X and V:  [29 77] 
Dot Product of X and Y: [[19 22]
 [50 58]]


In [22]:
#6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.vstack((v, w)).T
print(concat_xy_rows)
print(concat_vw_columns)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [23]:
#7
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print(concat_xv_error)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [24]:
#Problem-4: Matrix Operations
#1
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("\nA.A^-1:\n", I)


A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [25]:
#2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True


In [26]:
#3
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
AB_transpose = AB.transpose()
B_transpose = B.transpose()
A_transpose = A.transpose()
BT_AT = np.dot(B_transpose, A_transpose)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))


(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ: True


In [27]:
#Linear Equation
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])


# Using inverse method
X = np.dot(np.linalg.inv(A), B)
print("\nSolution using inverse method:\n", X)


# Using np.linalg.solve
X_solve = np.linalg.solve(A,B)
print("\nSolution using np.linalg.solve:\n", X_solve)


Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


In [28]:
import numpy as np
import time


# 1. Element-wise Addition
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)


start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
print("List element-wise addition time:", end_time - start_time)

start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
print("Numpy element-wise addition time:", end_time - start_time)

List element-wise addition time: 0.11978769302368164
Numpy element-wise addition time: 0.005004405975341797


In [29]:
# 2. Element-wise Multiplication
start_time = time.time()
list_mult = [x * y for x, y in zip(list1, list2)]
end_time = time.time()
print("List element-wise multiplication time:", end_time - start_time)




start_time = time.time()
array_mult = array1 * array2
end_time = time.time()
print("Numpy element-wise multiplication time:", end_time - start_time)

List element-wise multiplication time: 0.08618760108947754
Numpy element-wise multiplication time: 0.005960702896118164


In [30]:
# 3. Dot Product
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)
start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
end_time = time.time()
print("List dot product time:", end_time - start_time)


start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Numpy dot product time:", end_time - start_time)

List dot product time: 0.08821320533752441
Numpy dot product time: 0.001972198486328125


In [31]:
# 4. Matrix Multiplication
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)
size = 1000


# Using Python lists
matrix1 = [[j for j in range(size)] for i in range(size)]
matrix2 = [[j for j in range(size)] for i in range(size)]


start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()


print("Python list matrix multiplication time:", end_time - start_time)

# Using NumPy arrays
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)


start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()


print("NumPy matrix multiplication time:", end_time - start_time)

Python list matrix multiplication time: 198.38477611541748
NumPy matrix multiplication time: 2.1511104106903076
